name: Upload Website To S3

on:
  push:
    branches:
    - main

jobs:
  build:
    stage: build
    only:
      - main
    script:
      - yarn install
      - yarn build
    artifacts:
      paths:
        - dist/

  deploy:
    stage: deploy
    only:
      - main
    dependencies:
      - build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main branch
      uses: actions/checkout@main

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    script:
      - pip install awscli
      - aws s3 sync dist/ s3://${{ secrets.AWS_S3_BUCKET }} --delete